server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
billing:
  app: This is billing App API-Gatway default